main: nl.parrotlync.discovqueue.DiscovQueue
name: DiscovQueue
version: 2.1
description: Queue plugin for the Discovery Network
api-version: 1.12
depend: [Train_Carts]
author: ParrotLync
commands:
  queue:
    description: Main DiscovQueue command
    usage: /queue
    aliases: [q]
permissions:
  discovqueue.use:
    default: op
    description: Permission to use queues
  discovqueue.operate:
    default: op
    description: Operate queues
  discovqueue.manage:
    default: op
    description: Permission to manage / create queues