main: nl.parrotlync.discovqueue.DiscovQueue
name: DiscovQueue
version: 1.2.3
description: Queue plugin for the Discovery Network
api-version: 1.12
author: ParrotLync
commands:
  queue:
    description: Main DiscovQueue command
    usage: /queue
    aliases: [q]
permissions:
  queue.use:
    default: op
    description: Permission to use queues
  queue.manage:
    default: op
    description: Permission to manage / create queues