main: nl.parrotlync.discovqueue.DiscovQueue
name: ${artifactId}
version: ${version}
description: ${description}
api-version: 1.15
depend: [Train_Carts]
author: ParrotLync
commands:
  queue:
    description: Main DiscovQueue command
    usage: /queue
    aliases: [q]
permissions:
  discovqueue.use:
    default: op
    description: Permission to use queues
  discovqueue.operate:
    default: op
    description: Operate queues
  discovqueue.manage:
    default: op
    description: Permission to manage / create queues